languageCode: 'en-us'
description: 'Mapping the University is...'
title: 'Mapping the University'
baseURL: 'https://mtu.rrchnm.org'

permalinks:
  blog: "/:section/:slug/"
  page: "/:slug/"

taxonomies: false
pluralizelisttitles: false

markup:
  goldmark:
    renderer:
      unsafe: true
